services:
  eplsync:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUID: "${PUID:-1000}"
        PGID: "${PGID:-1000}"
    image: rlibanez/eplsync:0.0.1
    container_name: eplsync
    ports:
      - "${HOST_BIND:-127.0.0.1}:${HOST_PORT:-8088}:8088"
    volumes:
      - "${DATA_DIR:-./data}:/app/data"
      - "${LOGS_DIR:-./logs}:/app/logs"
    environment:
      TZ: "${TZ:-Europe/Madrid}"
    stop_grace_period: 30s
    restart: unless-stopped
